import { INITIAL_MUSCLE_GROUPS } from '../muscle-groups/muscle-group.constants.js';

export type MuscleGroupSlug = (typeof INITIAL_MUSCLE_GROUPS)[number]['slug'];

export interface CuratedExercise {
  name: string;
  slug: string;
  equipment: string;
  instructions: string;
  muscleGroup: MuscleGroupSlug;
}

function exercise(
  muscleGroup: MuscleGroupSlug,
  name: string,
  slug: string,
  equipment: string,
  instructions: string,
): CuratedExercise {
  return {
    name,
    slug,
    equipment,
    instructions,
    muscleGroup,
  };
}

export const CURATED_EXERCISE_COUNTS: Record<MuscleGroupSlug, number> = {
  gogus: 17,
  sirt: 19,
  omuz: 15,
  biceps: 13,
  triceps: 13,
  'on-kol': 9,
  bacak: 24,
  karin: 15,
};

export const CURATED_EXERCISES: readonly CuratedExercise[] = [
  // Göğüs — 17
  exercise(
    'gogus',
    'Barbell Bench Press',
    'barbell-bench-press',
    'Barbell',
    'Lower the bar to mid-chest with control, then press until the arms are extended.',
  ),
  exercise(
    'gogus',
    'Dumbbell Bench Press',
    'dumbbell-bench-press',
    'Dumbbells',
    'Press the dumbbells from chest level while keeping the shoulder blades pulled back.',
  ),
  exercise(
    'gogus',
    'Incline Barbell Bench Press',
    'incline-barbell-bench-press',
    'Barbell',
    'Use a moderate incline, lower the bar toward the upper chest, and press smoothly.',
  ),
  exercise(
    'gogus',
    'Incline Dumbbell Bench Press',
    'incline-dumbbell-bench-press',
    'Dumbbells',
    'Press upward from an inclined bench without letting the shoulders roll forward.',
  ),
  exercise(
    'gogus',
    'Decline Bench Press',
    'decline-bench-press',
    'Barbell',
    'Secure the legs, lower the bar to the lower chest, and press along the same path.',
  ),
  exercise(
    'gogus',
    'Smith Machine Bench Press',
    'smith-machine-bench-press',
    'Smith Machine',
    'Set the bench so the bar reaches mid-chest and press without lifting the shoulders.',
  ),
  exercise(
    'gogus',
    'Smith Machine Incline Press',
    'smith-machine-incline-press',
    'Smith Machine',
    'Position an incline bench under the bar and press from the upper chest with control.',
  ),
  exercise(
    'gogus',
    'Chest Press Machine',
    'chest-press-machine',
    'Machine',
    'Adjust the seat to chest-height handles and press forward without locking the elbows hard.',
  ),
  exercise(
    'gogus',
    'Incline Chest Press Machine',
    'incline-chest-press-machine',
    'Machine',
    'Keep the back against the pad and drive the handles upward through a comfortable range.',
  ),
  exercise(
    'gogus',
    'Dumbbell Fly',
    'dumbbell-fly',
    'Dumbbells',
    'Open the arms with soft elbows until the chest stretches, then bring the weights together.',
  ),
  exercise(
    'gogus',
    'Incline Dumbbell Fly',
    'incline-dumbbell-fly',
    'Dumbbells',
    'Use a low incline and sweep the dumbbells together while maintaining a fixed elbow bend.',
  ),
  exercise(
    'gogus',
    'Cable Fly',
    'cable-fly',
    'Cable',
    'Bring the handles together in front of the chest while keeping the torso still.',
  ),
  exercise(
    'gogus',
    'Low-to-High Cable Fly',
    'low-to-high-cable-fly',
    'Cable',
    'Sweep low handles upward toward eye level to emphasize the upper chest.',
  ),
  exercise(
    'gogus',
    'High-to-Low Cable Fly',
    'high-to-low-cable-fly',
    'Cable',
    'Pull high handles down and inward toward the lower chest without rounding the shoulders.',
  ),
  exercise(
    'gogus',
    'Pec Deck',
    'pec-deck',
    'Machine',
    'Keep the back supported and squeeze the pads together through the chest.',
  ),
  exercise(
    'gogus',
    'Push Up',
    'push-up',
    'Bodyweight',
    'Maintain a straight body line, lower the chest between the hands, and push the floor away.',
  ),
  exercise(
    'gogus',
    'Chest Dip',
    'chest-dip',
    'Bodyweight',
    'Lean slightly forward, descend under control, and press up while keeping the chest engaged.',
  ),

  // Sırt — 19
  exercise(
    'sirt',
    'Pull Up',
    'pull-up',
    'Bodyweight',
    'Pull the chest toward the bar while driving the elbows down, then lower fully under control.',
  ),
  exercise(
    'sirt',
    'Chin Up',
    'chin-up',
    'Bodyweight',
    'Use an underhand grip and pull until the chin clears the bar without swinging.',
  ),
  exercise(
    'sirt',
    'Wide Grip Lat Pulldown',
    'wide-grip-lat-pulldown',
    'Cable',
    'Pull the bar toward the upper chest while keeping the ribs down and shoulders away from ears.',
  ),
  exercise(
    'sirt',
    'Close Grip Lat Pulldown',
    'close-grip-lat-pulldown',
    'Cable',
    'Drive the elbows down and back as the close handle approaches the upper chest.',
  ),
  exercise(
    'sirt',
    'Neutral Grip Lat Pulldown',
    'neutral-grip-lat-pulldown',
    'Cable',
    'Use a neutral handle and pull to the chest without leaning excessively backward.',
  ),
  exercise(
    'sirt',
    'Straight Arm Pulldown',
    'straight-arm-pulldown',
    'Cable',
    'Keep the arms nearly straight and sweep the bar from shoulder height to the thighs.',
  ),
  exercise(
    'sirt',
    'Barbell Row',
    'barbell-row',
    'Barbell',
    'Hinge at the hips and row the bar toward the lower ribs without changing torso angle.',
  ),
  exercise(
    'sirt',
    'Pendlay Row',
    'pendlay-row',
    'Barbell',
    'Start each repetition from the floor and row explosively while keeping the back parallel.',
  ),
  exercise(
    'sirt',
    'Single Arm Dumbbell Row',
    'single-arm-dumbbell-row',
    'Dumbbell',
    'Brace on a bench and pull the dumbbell toward the hip without rotating the torso.',
  ),
  exercise(
    'sirt',
    'Chest Supported Dumbbell Row',
    'chest-supported-dumbbell-row',
    'Dumbbells',
    'Lie chest-down on an incline bench and row both dumbbells toward the ribs.',
  ),
  exercise(
    'sirt',
    'Seated Cable Row',
    'seated-cable-row',
    'Cable',
    'Sit tall and pull the handle to the abdomen while squeezing the shoulder blades together.',
  ),
  exercise(
    'sirt',
    'T-Bar Row',
    't-bar-row',
    'T-Bar Machine',
    'Brace the torso and row the handles toward the chest without shrugging.',
  ),
  exercise(
    'sirt',
    'Machine Row',
    'machine-row',
    'Machine',
    'Keep the chest on the pad and pull the handles back until the shoulder blades retract.',
  ),
  exercise(
    'sirt',
    'Smith Machine Row',
    'smith-machine-row',
    'Smith Machine',
    'Hinge into position and row the guided bar toward the lower ribs with a stable torso.',
  ),
  exercise(
    'sirt',
    'Deadlift',
    'deadlift',
    'Barbell',
    'Brace the trunk and stand with the bar by extending the hips and knees together.',
  ),
  exercise(
    'sirt',
    'Rack Pull',
    'rack-pull',
    'Barbell',
    'Pull from safety pins around knee height and finish by standing tall without leaning back.',
  ),
  exercise(
    'sirt',
    'Back Extension',
    'back-extension',
    'Roman Chair',
    'Hinge at the hips, lower with a neutral spine, and rise until the body forms a straight line.',
  ),
  exercise(
    'sirt',
    'Inverted Row',
    'inverted-row',
    'Bodyweight',
    'Keep the body rigid and pull the chest to the bar before lowering with control.',
  ),
  exercise(
    'sirt',
    'Dumbbell Pullover',
    'dumbbell-pullover',
    'Dumbbell',
    'Lower one dumbbell behind the head with soft elbows, then pull it back over the chest.',
  ),

  // Omuz — 15
  exercise(
    'omuz',
    'Barbell Overhead Press',
    'barbell-overhead-press',
    'Barbell',
    'Brace the trunk and press the bar overhead while keeping it close to the face.',
  ),
  exercise(
    'omuz',
    'Dumbbell Shoulder Press',
    'dumbbell-shoulder-press',
    'Dumbbells',
    'Press the dumbbells overhead from shoulder height without overextending the lower back.',
  ),
  exercise(
    'omuz',
    'Arnold Press',
    'arnold-press',
    'Dumbbells',
    'Rotate the palms outward as the dumbbells travel from the chest to overhead.',
  ),
  exercise(
    'omuz',
    'Machine Shoulder Press',
    'machine-shoulder-press',
    'Machine',
    'Set the handles near shoulder height and press overhead while staying against the pad.',
  ),
  exercise(
    'omuz',
    'Smith Machine Shoulder Press',
    'smith-machine-shoulder-press',
    'Smith Machine',
    'Place the bench under the bar and press vertically without letting the elbows drift far back.',
  ),
  exercise(
    'omuz',
    'Dumbbell Lateral Raise',
    'dumbbell-lateral-raise',
    'Dumbbells',
    'Raise the dumbbells to shoulder height with soft elbows and controlled momentum.',
  ),
  exercise(
    'omuz',
    'Cable Lateral Raise',
    'cable-lateral-raise',
    'Cable',
    'Lift the cable out to the side while keeping the shoulder down and torso still.',
  ),
  exercise(
    'omuz',
    'Machine Lateral Raise',
    'machine-lateral-raise',
    'Machine',
    'Keep the elbows against the pads and raise them until roughly level with the shoulders.',
  ),
  exercise(
    'omuz',
    'Dumbbell Front Raise',
    'dumbbell-front-raise',
    'Dumbbells',
    'Raise the dumbbells in front to shoulder height without leaning backward.',
  ),
  exercise(
    'omuz',
    'Cable Front Raise',
    'cable-front-raise',
    'Cable',
    'Lift the handle forward to shoulder height while maintaining a stable ribcage.',
  ),
  exercise(
    'omuz',
    'Bent Over Rear Delt Fly',
    'bent-over-rear-delt-fly',
    'Dumbbells',
    'Hinge forward and open the arms wide while keeping the shoulder blades controlled.',
  ),
  exercise(
    'omuz',
    'Reverse Pec Deck',
    'reverse-pec-deck',
    'Machine',
    'Face the pad and sweep the handles outward without shrugging the shoulders.',
  ),
  exercise(
    'omuz',
    'Face Pull',
    'face-pull',
    'Cable',
    'Pull the rope toward the face with high elbows and rotate the hands apart.',
  ),
  exercise(
    'omuz',
    'Upright Row',
    'upright-row',
    'EZ Bar',
    'Pull the bar toward the upper chest with elbows leading and stop at a comfortable height.',
  ),
  exercise(
    'omuz',
    'Landmine Press',
    'landmine-press',
    'Landmine',
    'Press the bar upward and forward from shoulder height while keeping the ribs stacked.',
  ),

  // Biceps — 13
  exercise(
    'biceps',
    'Barbell Curl',
    'barbell-curl',
    'Barbell',
    'Curl the bar without swinging the torso, then lower until the elbows are extended.',
  ),
  exercise(
    'biceps',
    'EZ Bar Curl',
    'ez-bar-curl',
    'EZ Bar',
    'Keep the elbows near the sides and curl through a comfortable wrist angle.',
  ),
  exercise(
    'biceps',
    'Dumbbell Curl',
    'dumbbell-curl',
    'Dumbbells',
    'Curl both dumbbells with the palms turning upward and avoid moving the upper arms.',
  ),
  exercise(
    'biceps',
    'Alternating Dumbbell Curl',
    'alternating-dumbbell-curl',
    'Dumbbells',
    'Curl one dumbbell at a time while keeping the non-working arm still.',
  ),
  exercise(
    'biceps',
    'Hammer Curl',
    'hammer-curl',
    'Dumbbells',
    'Maintain a neutral grip and curl without letting the elbows travel forward.',
  ),
  exercise(
    'biceps',
    'Cross Body Hammer Curl',
    'cross-body-hammer-curl',
    'Dumbbells',
    'Curl each dumbbell toward the opposite side of the chest with a neutral grip.',
  ),
  exercise(
    'biceps',
    'Incline Dumbbell Curl',
    'incline-dumbbell-curl',
    'Dumbbells',
    'Let the arms hang behind the torso and curl without lifting the elbows.',
  ),
  exercise(
    'biceps',
    'Preacher Curl',
    'preacher-curl',
    'EZ Bar',
    'Keep the upper arms on the pad and curl without losing tension at the bottom.',
  ),
  exercise(
    'biceps',
    'Machine Preacher Curl',
    'machine-preacher-curl',
    'Machine',
    'Align the elbows with the machine pivot and curl through a controlled range.',
  ),
  exercise(
    'biceps',
    'Cable Curl',
    'cable-curl',
    'Cable',
    'Keep the elbows pinned and curl the cable handle toward the shoulders.',
  ),
  exercise(
    'biceps',
    'Bayesian Cable Curl',
    'bayesian-cable-curl',
    'Cable',
    'Stand ahead of a low cable and curl while the working arm stays behind the torso.',
  ),
  exercise(
    'biceps',
    'Concentration Curl',
    'concentration-curl',
    'Dumbbell',
    'Brace the elbow against the inner thigh and curl without rotating the shoulder.',
  ),
  exercise(
    'biceps',
    'Spider Curl',
    'spider-curl',
    'EZ Bar',
    'Lie chest-down on an incline bench and curl while the upper arms point downward.',
  ),

  // Triceps — 13
  exercise(
    'triceps',
    'Cable Pushdown',
    'cable-pushdown',
    'Cable',
    'Keep the elbows fixed at the sides and extend the bar until the arms are straight.',
  ),
  exercise(
    'triceps',
    'Rope Pushdown',
    'rope-pushdown',
    'Cable',
    'Extend the elbows and separate the rope ends slightly at the bottom.',
  ),
  exercise(
    'triceps',
    'Reverse Grip Pushdown',
    'reverse-grip-pushdown',
    'Cable',
    'Use an underhand grip and extend the elbows while keeping the wrists neutral.',
  ),
  exercise(
    'triceps',
    'Overhead Cable Triceps Extension',
    'overhead-cable-triceps-extension',
    'Cable',
    'Keep the upper arms beside the head and extend the elbows against cable tension.',
  ),
  exercise(
    'triceps',
    'Dumbbell Overhead Triceps Extension',
    'dumbbell-overhead-triceps-extension',
    'Dumbbell',
    'Lower the dumbbell behind the head and extend without flaring the elbows excessively.',
  ),
  exercise(
    'triceps',
    'Lying Triceps Extension',
    'lying-triceps-extension',
    'Barbell',
    'Lower the bar behind the forehead by bending only the elbows, then extend fully.',
  ),
  exercise(
    'triceps',
    'EZ Bar Skull Crusher',
    'ez-bar-skull-crusher',
    'EZ Bar',
    'Lower the EZ bar toward the forehead with steady upper arms and extend the elbows.',
  ),
  exercise(
    'triceps',
    'Close Grip Bench Press',
    'close-grip-bench-press',
    'Barbell',
    'Use a shoulder-width grip, lower to the chest, and press while keeping elbows controlled.',
  ),
  exercise(
    'triceps',
    'Machine Triceps Extension',
    'machine-triceps-extension',
    'Machine',
    'Align the elbows with the pivot and extend the handles through a controlled range.',
  ),
  exercise(
    'triceps',
    'Triceps Dip',
    'triceps-dip',
    'Bodyweight',
    'Keep the torso relatively upright and press from the bottom by extending the elbows.',
  ),
  exercise(
    'triceps',
    'Single Arm Cable Extension',
    'single-arm-cable-extension',
    'Cable',
    'Extend one arm at a time while keeping the shoulder and upper arm still.',
  ),
  exercise(
    'triceps',
    'Dumbbell Triceps Kickback',
    'dumbbell-triceps-kickback',
    'Dumbbell',
    'Hold the upper arm parallel to the torso and straighten the elbow completely.',
  ),
  exercise(
    'triceps',
    'JM Press',
    'jm-press',
    'Barbell',
    'Lower the bar toward the upper chest by bending the elbows, then press back up.',
  ),

  // Ön Kol — 9
  exercise(
    'on-kol',
    'Seated Wrist Curl',
    'seated-wrist-curl',
    'Barbell',
    'Support the forearms on the thighs and curl the wrists through a comfortable range.',
  ),
  exercise(
    'on-kol',
    'Reverse Wrist Curl',
    'reverse-wrist-curl',
    'Barbell',
    'With palms down and forearms supported, raise the backs of the hands slowly.',
  ),
  exercise(
    'on-kol',
    'Reverse Barbell Curl',
    'reverse-barbell-curl',
    'Barbell',
    'Curl with an overhand grip while keeping the elbows close to the torso.',
  ),
  exercise(
    'on-kol',
    'Behind-the-Back Wrist Curl',
    'behind-the-back-wrist-curl',
    'Barbell',
    'Hold the bar behind the hips and flex the wrists without moving the elbows.',
  ),
  exercise(
    'on-kol',
    "Farmer's Carry",
    'farmers-carry',
    'Dumbbells',
    'Walk with heavy dumbbells while staying tall and maintaining a secure grip.',
  ),
  exercise(
    'on-kol',
    'Plate Pinch',
    'plate-pinch',
    'Weight Plates',
    'Pinch smooth-sided plates together and hold them without letting the shoulders sag.',
  ),
  exercise(
    'on-kol',
    'Wrist Roller',
    'wrist-roller',
    'Wrist Roller',
    'Roll the weight upward and downward using controlled alternating wrist movements.',
  ),
  exercise(
    'on-kol',
    'Dead Hang',
    'dead-hang',
    'Pull-Up Bar',
    'Hang with a firm grip and controlled shoulders for the prescribed time.',
  ),
  exercise(
    'on-kol',
    'Towel Grip Hang',
    'towel-grip-hang',
    'Towel and Pull-Up Bar',
    'Hang from two towels with a tight grip while keeping the shoulders stable.',
  ),

  // Bacak — 24
  exercise(
    'bacak',
    'Back Squat',
    'back-squat',
    'Barbell',
    'Brace the trunk, sit between the hips, and stand by driving through the whole foot.',
  ),
  exercise(
    'bacak',
    'Front Squat',
    'front-squat',
    'Barbell',
    'Keep the elbows high, descend with an upright torso, and drive upward through the feet.',
  ),
  exercise(
    'bacak',
    'Hack Squat',
    'hack-squat',
    'Machine',
    'Keep the back on the pad, descend under control, and press through the platform.',
  ),
  exercise(
    'bacak',
    'Smith Machine Squat',
    'smith-machine-squat',
    'Smith Machine',
    'Set the feet for balance, squat to a comfortable depth, and drive the bar upward.',
  ),
  exercise(
    'bacak',
    'Leg Press',
    'leg-press',
    'Machine',
    'Lower the sled until the hips remain supported, then press without locking the knees hard.',
  ),
  exercise(
    'bacak',
    'Bulgarian Split Squat',
    'bulgarian-split-squat',
    'Dumbbells',
    'Elevate the rear foot, lower the back knee, and stand through the front leg.',
  ),
  exercise(
    'bacak',
    'Walking Lunge',
    'walking-lunge',
    'Dumbbells',
    'Step forward into each lunge and push through the lead foot to continue walking.',
  ),
  exercise(
    'bacak',
    'Reverse Lunge',
    'reverse-lunge',
    'Dumbbells',
    'Step backward, lower the rear knee, and return by driving through the front foot.',
  ),
  exercise(
    'bacak',
    'Step Up',
    'step-up',
    'Dumbbells',
    'Place one foot fully on the box and stand without pushing excessively from the trailing leg.',
  ),
  exercise(
    'bacak',
    'Leg Extension',
    'leg-extension',
    'Machine',
    'Align the knee with the machine pivot and extend the legs without bouncing.',
  ),
  exercise(
    'bacak',
    'Romanian Deadlift',
    'romanian-deadlift',
    'Barbell',
    'Push the hips back with soft knees and stand once the hamstrings reach a strong stretch.',
  ),
  exercise(
    'bacak',
    'Stiff Leg Deadlift',
    'stiff-leg-deadlift',
    'Barbell',
    'Hinge with nearly straight legs and keep the bar close before extending the hips.',
  ),
  exercise(
    'bacak',
    'Lying Leg Curl',
    'lying-leg-curl',
    'Machine',
    'Keep the hips against the pad and curl the heels toward the glutes.',
  ),
  exercise(
    'bacak',
    'Seated Leg Curl',
    'seated-leg-curl',
    'Machine',
    'Secure the thigh pad and curl the lower legs beneath the seat with control.',
  ),
  exercise(
    'bacak',
    'Standing Leg Curl',
    'standing-leg-curl',
    'Machine',
    'Curl one heel upward while keeping the hips square and the standing leg stable.',
  ),
  exercise(
    'bacak',
    'Barbell Hip Thrust',
    'barbell-hip-thrust',
    'Barbell',
    'Drive the hips upward from a bench and finish with the ribs down and glutes squeezed.',
  ),
  exercise(
    'bacak',
    'Glute Bridge',
    'glute-bridge',
    'Bodyweight',
    'Press through the feet and lift the hips until the torso and thighs align.',
  ),
  exercise(
    'bacak',
    'Cable Glute Kickback',
    'cable-glute-kickback',
    'Cable',
    'Extend one hip backward against the cable without arching the lower back.',
  ),
  exercise(
    'bacak',
    'Hip Abduction Machine',
    'hip-abduction-machine',
    'Machine',
    'Press the knees outward against the pads while keeping the pelvis stable.',
  ),
  exercise(
    'bacak',
    'Hip Adduction Machine',
    'hip-adduction-machine',
    'Machine',
    'Bring the knees inward against resistance without bouncing at the end range.',
  ),
  exercise(
    'bacak',
    'Standing Calf Raise',
    'standing-calf-raise',
    'Machine',
    'Rise onto the balls of the feet, pause at the top, and lower through a full stretch.',
  ),
  exercise(
    'bacak',
    'Seated Calf Raise',
    'seated-calf-raise',
    'Machine',
    'Lift the heels against the thigh pad, pause, and lower slowly.',
  ),
  exercise(
    'bacak',
    'Leg Press Calf Raise',
    'leg-press-calf-raise',
    'Leg Press',
    'Move the sled only through the ankles while keeping the knees slightly unlocked.',
  ),
  exercise(
    'bacak',
    'Goblet Squat',
    'goblet-squat',
    'Dumbbell',
    'Hold the weight at the chest, squat between the hips, and stand tall.',
  ),

  // Karın — 15
  exercise(
    'karin',
    'Crunch',
    'crunch',
    'Bodyweight',
    'Curl the ribs toward the pelvis without pulling on the neck.',
  ),
  exercise(
    'karin',
    'Cable Crunch',
    'cable-crunch',
    'Cable',
    'Kneel and flex the trunk so the ribs move toward the pelvis against the cable.',
  ),
  exercise(
    'karin',
    'Machine Crunch',
    'machine-crunch',
    'Machine',
    'Brace into the pads and shorten the torso without driving the movement from the hips.',
  ),
  exercise(
    'karin',
    'Reverse Crunch',
    'reverse-crunch',
    'Bodyweight',
    'Curl the pelvis toward the ribs while keeping the movement slow and controlled.',
  ),
  exercise(
    'karin',
    'Hanging Knee Raise',
    'hanging-knee-raise',
    'Pull-Up Bar',
    'Raise the knees toward the chest without swinging, then lower under control.',
  ),
  exercise(
    'karin',
    'Hanging Leg Raise',
    'hanging-leg-raise',
    'Pull-Up Bar',
    'Lift straight legs toward the torso while minimizing momentum and lower slowly.',
  ),
  exercise(
    'karin',
    'Lying Leg Raise',
    'lying-leg-raise',
    'Bodyweight',
    'Raise the legs while keeping the lower back controlled against the floor.',
  ),
  exercise(
    'karin',
    'Ab Wheel Rollout',
    'ab-wheel-rollout',
    'Ab Wheel',
    'Roll forward while resisting lower-back extension, then pull back using the trunk.',
  ),
  exercise(
    'karin',
    'Plank',
    'plank',
    'Bodyweight',
    'Hold a straight line from head to heels while bracing the abdomen and glutes.',
  ),
  exercise(
    'karin',
    'Side Plank',
    'side-plank',
    'Bodyweight',
    'Support the body on one forearm and hold the hips in a straight stacked position.',
  ),
  exercise(
    'karin',
    'Russian Twist',
    'russian-twist',
    'Medicine Ball',
    'Rotate the ribcage from side to side while keeping the hips and legs controlled.',
  ),
  exercise(
    'karin',
    'Bicycle Crunch',
    'bicycle-crunch',
    'Bodyweight',
    'Alternate bringing each shoulder toward the opposite knee without pulling the neck.',
  ),
  exercise(
    'karin',
    'Mountain Climber',
    'mountain-climber',
    'Bodyweight',
    'From a plank, drive alternating knees forward while keeping the shoulders over the hands.',
  ),
  exercise(
    'karin',
    'Decline Sit Up',
    'decline-sit-up',
    'Decline Bench',
    'Curl up the decline bench under control and lower without dropping backward.',
  ),
  exercise(
    'karin',
    'Pallof Press',
    'pallof-press',
    'Cable',
    'Press the handle away from the chest while resisting rotation from the cable.',
  ),
];
