// Generated from USDA FoodData Central, SR Legacy (public domain, CC0):
// https://fdc.nal.usda.gov/. Turkish names, aliases, and servings were added
// by hand. Values are per 100 g of the food as described in the name.
import type { CatalogFoodRecord } from './food-catalog.js';

export const FOOD_CATALOG_DATA: readonly CatalogFoodRecord[] = [
  {
    id: 'usda-171477',
    name: 'Tavuk göğsü (pişmiş)',
    category: 'Et ve tavuk',
    aliases: 'tavuk piliç göğüs chicken breast',
    calories: 165,
    proteinG: 31,
    carbsG: 0,
    fatG: 3.6,
    servingLabel: '1 porsiyon (120 g)',
    servingGrams: 120,
  },
  {
    id: 'usda-171077',
    name: 'Tavuk göğsü (çiğ)',
    category: 'Et ve tavuk',
    aliases: 'tavuk piliç göğüs chicken breast raw',
    calories: 120,
    proteinG: 22.5,
    carbsG: 0,
    fatG: 2.6,
    servingLabel: '1 porsiyon (150 g)',
    servingGrams: 150,
  },
  {
    id: 'usda-172388',
    name: 'Tavuk but (pişmiş, derisiz)',
    category: 'Et ve tavuk',
    aliases: 'tavuk piliç but incik chicken thigh',
    calories: 179,
    proteinG: 24.8,
    carbsG: 0,
    fatG: 8.2,
    servingLabel: '1 adet (90 g)',
    servingGrams: 90,
  },
  {
    id: 'usda-171496',
    name: 'Hindi göğsü (pişmiş)',
    category: 'Et ve tavuk',
    aliases: 'hindi göğüs turkey breast',
    calories: 147,
    proteinG: 30.1,
    carbsG: 0,
    fatG: 2.1,
    servingLabel: '1 porsiyon (100 g)',
    servingGrams: 100,
  },
  {
    id: 'usda-171793',
    name: 'Dana kıyma (%10 yağlı, pişmiş)',
    category: 'Et ve tavuk',
    aliases: 'dana kıyma köfte et ground beef',
    calories: 204,
    proteinG: 25.2,
    carbsG: 0,
    fatG: 10.7,
    servingLabel: '1 köfte (85 g)',
    servingGrams: 85,
  },
  {
    id: 'usda-174033',
    name: 'Dana kıyma (%15 yağlı, pişmiş)',
    category: 'Et ve tavuk',
    aliases: 'dana kıyma köfte et ground beef',
    calories: 232,
    proteinG: 24.6,
    carbsG: 0,
    fatG: 14,
    servingLabel: '1 köfte (85 g)',
    servingGrams: 85,
  },
  {
    id: 'usda-172544',
    name: 'Kuzu kıyma (pişmiş)',
    category: 'Et ve tavuk',
    aliases: 'kuzu kıyma köfte lamb ground',
    calories: 283,
    proteinG: 24.8,
    carbsG: 0,
    fatG: 19.7,
    servingLabel: '1 porsiyon (85 g)',
    servingGrams: 85,
  },
  {
    id: 'usda-168634',
    name: 'Dana biftek (pişmiş, yağsız)',
    category: 'Et ve tavuk',
    aliases: 'dana biftek bonfile antrikot et steak sirloin',
    calories: 183,
    proteinG: 30.6,
    carbsG: 0,
    fatG: 5.8,
    servingLabel: '1 porsiyon (120 g)',
    servingGrams: 120,
  },
  {
    id: 'usda-168627',
    name: 'Dana ciğer (tavada)',
    category: 'Et ve tavuk',
    aliases: 'ciğer dana ciğeri liver',
    calories: 175,
    proteinG: 26.5,
    carbsG: 5.2,
    fatG: 4.7,
    servingLabel: '1 porsiyon (85 g)',
    servingGrams: 85,
  },
  {
    id: 'usda-172935',
    name: 'Salam (dana)',
    category: 'Et ve tavuk',
    aliases: 'salam beef salami',
    calories: 261,
    proteinG: 12.6,
    carbsG: 1.9,
    fatG: 22.2,
    servingLabel: '1 dilim (26 g)',
    servingGrams: 26,
  },
  {
    id: 'usda-172937',
    name: 'Hindi salam',
    category: 'Et ve tavuk',
    aliases: 'hindi salam turkey salami jambon',
    calories: 172,
    proteinG: 19.2,
    carbsG: 1.6,
    fatG: 9.2,
    servingLabel: '1 dilim (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-175168',
    name: 'Somon (pişmiş)',
    category: 'Balık',
    aliases: 'somon salmon balık',
    calories: 206,
    proteinG: 22.1,
    carbsG: 0,
    fatG: 12.4,
    servingLabel: '1 fileto (150 g)',
    servingGrams: 150,
  },
  {
    id: 'usda-171986',
    name: 'Ton balığı (konserve, suda)',
    category: 'Balık',
    aliases: 'ton balık tuna konserve',
    calories: 116,
    proteinG: 25.5,
    carbsG: 0,
    fatG: 0.8,
    servingLabel: '1 küçük kutu (80 g)',
    servingGrams: 80,
  },
  {
    id: 'usda-174182',
    name: 'Hamsi (çiğ)',
    category: 'Balık',
    aliases: 'hamsi anchovy balık',
    calories: 131,
    proteinG: 20.4,
    carbsG: 0,
    fatG: 4.8,
    servingLabel: '5 adet (75 g)',
    servingGrams: 75,
  },
  {
    id: 'usda-175139',
    name: 'Sardalya (konserve, yağlı)',
    category: 'Balık',
    aliases: 'sardalya sardine balık konserve',
    calories: 208,
    proteinG: 24.6,
    carbsG: 0,
    fatG: 11.5,
    servingLabel: '1 kutu (90 g)',
    servingGrams: 90,
  },
  {
    id: 'usda-175180',
    name: 'Karides (pişmiş)',
    category: 'Balık',
    aliases: 'karides shrimp deniz ürünleri',
    calories: 99,
    proteinG: 24,
    carbsG: 0.2,
    fatG: 0.3,
    servingLabel: '1 porsiyon (85 g)',
    servingGrams: 85,
  },
  {
    id: 'usda-174228',
    name: 'Levrek (pişmiş)',
    category: 'Balık',
    aliases: 'levrek çipura sea bass balık',
    calories: 124,
    proteinG: 22.7,
    carbsG: 0,
    fatG: 3,
    servingLabel: '1 fileto (120 g)',
    servingGrams: 120,
  },
  {
    id: 'usda-173718',
    name: 'Alabalık (pişmiş)',
    category: 'Balık',
    aliases: 'alabalık trout balık',
    calories: 168,
    proteinG: 23.8,
    carbsG: 0,
    fatG: 7.4,
    servingLabel: '1 fileto (120 g)',
    servingGrams: 120,
  },
  {
    id: 'usda-175120',
    name: 'Uskumru (pişmiş)',
    category: 'Balık',
    aliases: 'uskumru mackerel balık',
    calories: 262,
    proteinG: 23.9,
    carbsG: 0,
    fatG: 17.8,
    servingLabel: '1 fileto (100 g)',
    servingGrams: 100,
  },
  {
    id: 'usda-173424',
    name: 'Yumurta (haşlanmış)',
    category: 'Yumurta',
    aliases: 'yumurta haşlanmış egg boiled',
    calories: 155,
    proteinG: 12.6,
    carbsG: 1.1,
    fatG: 10.6,
    servingLabel: '1 adet (50 g)',
    servingGrams: 50,
  },
  {
    id: 'usda-171287',
    name: 'Yumurta (çiğ)',
    category: 'Yumurta',
    aliases: 'yumurta egg raw',
    calories: 143,
    proteinG: 12.6,
    carbsG: 0.7,
    fatG: 9.5,
    servingLabel: '1 adet (50 g)',
    servingGrams: 50,
  },
  {
    id: 'usda-173423',
    name: 'Sahanda yumurta',
    category: 'Yumurta',
    aliases: 'yumurta sahanda egg fried',
    calories: 196,
    proteinG: 13.6,
    carbsG: 0.8,
    fatG: 14.8,
    servingLabel: '1 adet (46 g)',
    servingGrams: 46,
  },
  {
    id: 'usda-172185',
    name: 'Omlet',
    category: 'Yumurta',
    aliases: 'omlet yumurta omelet',
    calories: 154,
    proteinG: 10.6,
    carbsG: 0.6,
    fatG: 11.7,
    servingLabel: '1 porsiyon (61 g)',
    servingGrams: 61,
  },
  {
    id: 'usda-172187',
    name: 'Çırpılmış yumurta',
    category: 'Yumurta',
    aliases: 'yumurta çırpılmış scrambled menemen',
    calories: 149,
    proteinG: 10,
    carbsG: 1.6,
    fatG: 11,
    servingLabel: '1 porsiyon (61 g)',
    servingGrams: 61,
  },
  {
    id: 'usda-172183',
    name: 'Yumurta akı (çiğ)',
    category: 'Yumurta',
    aliases: 'yumurta akı beyazı egg white',
    calories: 52,
    proteinG: 10.9,
    carbsG: 0.7,
    fatG: 0.2,
    servingLabel: '1 adet (33 g)',
    servingGrams: 33,
  },
  {
    id: 'usda-171265',
    name: 'Süt (tam yağlı)',
    category: 'Süt ürünleri',
    aliases: 'süt whole milk',
    calories: 61,
    proteinG: 3.2,
    carbsG: 4.8,
    fatG: 3.3,
    servingLabel: '1 su bardağı (244 g)',
    servingGrams: 244,
  },
  {
    id: 'usda-171267',
    name: 'Süt (yarım yağlı)',
    category: 'Süt ürünleri',
    aliases: 'süt reduced fat 2% milk',
    calories: 50,
    proteinG: 3.3,
    carbsG: 4.8,
    fatG: 2,
    servingLabel: '1 su bardağı (244 g)',
    servingGrams: 244,
  },
  {
    id: 'usda-171269',
    name: 'Süt (yağsız)',
    category: 'Süt ürünleri',
    aliases: 'süt yağsız skim nonfat milk',
    calories: 34,
    proteinG: 3.4,
    carbsG: 5,
    fatG: 0.1,
    servingLabel: '1 su bardağı (245 g)',
    servingGrams: 245,
  },
  {
    id: 'usda-171284',
    name: 'Yoğurt (tam yağlı)',
    category: 'Süt ürünleri',
    aliases: 'yoğurt yogurt tam yağlı',
    calories: 61,
    proteinG: 3.5,
    carbsG: 4.7,
    fatG: 3.3,
    servingLabel: '1 kase (200 g)',
    servingGrams: 200,
  },
  {
    id: 'usda-170886',
    name: 'Yoğurt (az yağlı)',
    category: 'Süt ürünleri',
    aliases: 'yoğurt yogurt light az yağlı',
    calories: 63,
    proteinG: 5.3,
    carbsG: 7,
    fatG: 1.6,
    servingLabel: '1 kase (200 g)',
    servingGrams: 200,
  },
  {
    id: 'usda-170894',
    name: 'Süzme yoğurt (yağsız)',
    category: 'Süt ürünleri',
    aliases: 'süzme yoğurt yunan greek yogurt',
    calories: 59,
    proteinG: 10.2,
    carbsG: 3.6,
    fatG: 0.4,
    servingLabel: '1 kase (170 g)',
    servingGrams: 170,
  },
  {
    id: 'usda-170904',
    name: 'Kefir',
    category: 'Süt ürünleri',
    aliases: 'kefir',
    calories: 43,
    proteinG: 3.8,
    carbsG: 4.8,
    fatG: 1,
    servingLabel: '1 su bardağı (243 g)',
    servingGrams: 243,
  },
  {
    id: 'usda-173420',
    name: 'Beyaz peynir',
    category: 'Süt ürünleri',
    aliases: 'beyaz peynir feta',
    calories: 265,
    proteinG: 14.2,
    carbsG: 3.9,
    fatG: 21.5,
    servingLabel: '1 dilim (30 g)',
    servingGrams: 30,
  },
  {
    id: 'usda-172182',
    name: 'Lor / süzme peynir',
    category: 'Süt ürünleri',
    aliases: 'lor peyniri süzme peynir cottage',
    calories: 81,
    proteinG: 10.5,
    carbsG: 4.8,
    fatG: 2.3,
    servingLabel: '1 kase (113 g)',
    servingGrams: 113,
  },
  {
    id: 'usda-170846',
    name: 'Mozzarella',
    category: 'Süt ürünleri',
    aliases: 'mozzarella peynir pizza peyniri',
    calories: 318,
    proteinG: 21.6,
    carbsG: 2.5,
    fatG: 24.6,
    servingLabel: '1 dilim (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-170899',
    name: 'Kaşar / Cheddar peyniri',
    category: 'Süt ürünleri',
    aliases: 'kaşar peyniri cheddar taze kaşar eski kaşar',
    calories: 410,
    proteinG: 24.3,
    carbsG: 2.1,
    fatG: 33.8,
    servingLabel: '1 dilim (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-173418',
    name: 'Krem peynir',
    category: 'Süt ürünleri',
    aliases: 'krem peynir labne cream cheese',
    calories: 350,
    proteinG: 6.2,
    carbsG: 5.5,
    fatG: 34.4,
    servingLabel: '1 yemek kaşığı (14 g)',
    servingGrams: 14,
  },
  {
    id: 'usda-173410',
    name: 'Tereyağı',
    category: 'Süt ürünleri',
    aliases: 'tereyağı butter',
    calories: 717,
    proteinG: 0.9,
    carbsG: 0.1,
    fatG: 81.1,
    servingLabel: '1 yemek kaşığı (14 g)',
    servingGrams: 14,
  },
  {
    id: 'usda-168878',
    name: 'Pirinç pilavı (pişmiş)',
    category: 'Tahıl ve ekmek',
    aliases: 'pirinç pilav rice',
    calories: 130,
    proteinG: 2.7,
    carbsG: 28.2,
    fatG: 0.3,
    servingLabel: '1 tabak (150 g)',
    servingGrams: 150,
  },
  {
    id: 'usda-168877',
    name: 'Pirinç (çiğ)',
    category: 'Tahıl ve ekmek',
    aliases: 'pirinç rice çiğ kuru',
    calories: 365,
    proteinG: 7.1,
    carbsG: 80,
    fatG: 0.7,
    servingLabel: '1 su bardağı (185 g)',
    servingGrams: 185,
  },
  {
    id: 'usda-169704',
    name: 'Esmer pirinç (pişmiş)',
    category: 'Tahıl ve ekmek',
    aliases: 'esmer pirinç brown rice',
    calories: 123,
    proteinG: 2.7,
    carbsG: 25.6,
    fatG: 1,
    servingLabel: '1 tabak (150 g)',
    servingGrams: 150,
  },
  {
    id: 'usda-170287',
    name: 'Bulgur pilavı (pişmiş)',
    category: 'Tahıl ve ekmek',
    aliases: 'bulgur pilavı bulgur',
    calories: 83,
    proteinG: 3.1,
    carbsG: 18.6,
    fatG: 0.2,
    servingLabel: '1 tabak (150 g)',
    servingGrams: 150,
  },
  {
    id: 'usda-170688',
    name: 'Bulgur (kuru)',
    category: 'Tahıl ve ekmek',
    aliases: 'bulgur kuru çiğ',
    calories: 342,
    proteinG: 12.3,
    carbsG: 75.9,
    fatG: 1.3,
    servingLabel: '1 su bardağı (140 g)',
    servingGrams: 140,
  },
  {
    id: 'usda-169737',
    name: 'Makarna (pişmiş)',
    category: 'Tahıl ve ekmek',
    aliases: 'makarna spagetti pasta',
    calories: 158,
    proteinG: 5.8,
    carbsG: 30.9,
    fatG: 0.9,
    servingLabel: '1 tabak (140 g)',
    servingGrams: 140,
  },
  {
    id: 'usda-169736',
    name: 'Makarna (kuru)',
    category: 'Tahıl ve ekmek',
    aliases: 'makarna spagetti pasta kuru çiğ',
    calories: 371,
    proteinG: 13,
    carbsG: 74.7,
    fatG: 1.5,
    servingLabel: '1 porsiyon (75 g)',
    servingGrams: 75,
  },
  {
    id: 'usda-172688',
    name: 'Tam buğday ekmeği',
    category: 'Tahıl ve ekmek',
    aliases: 'ekmek tam buğday tam tahıllı whole wheat bread',
    calories: 252,
    proteinG: 12.5,
    carbsG: 42.7,
    fatG: 3.5,
    servingLabel: '1 dilim (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-174924',
    name: 'Beyaz ekmek',
    category: 'Tahıl ve ekmek',
    aliases: 'ekmek beyaz white bread',
    calories: 266,
    proteinG: 8.9,
    carbsG: 49.4,
    fatG: 3.3,
    servingLabel: '1 dilim (29 g)',
    servingGrams: 29,
  },
  {
    id: 'usda-173904',
    name: 'Yulaf ezmesi (kuru)',
    category: 'Tahıl ve ekmek',
    aliases: 'yulaf ezmesi yulaf oats oatmeal',
    calories: 379,
    proteinG: 13.2,
    carbsG: 67.7,
    fatG: 6.5,
    servingLabel: '5 yemek kaşığı (40 g)',
    servingGrams: 40,
  },
  {
    id: 'usda-171675',
    name: 'Yulaf lapası (suyla pişmiş)',
    category: 'Tahıl ve ekmek',
    aliases: 'yulaf lapası yulaf porridge oatmeal',
    calories: 71,
    proteinG: 2.5,
    carbsG: 12,
    fatG: 1.5,
    servingLabel: '1 kase (234 g)',
    servingGrams: 234,
  },
  {
    id: 'usda-168917',
    name: 'Kinoa (pişmiş)',
    category: 'Tahıl ve ekmek',
    aliases: 'kinoa quinoa',
    calories: 120,
    proteinG: 4.4,
    carbsG: 21.3,
    fatG: 1.9,
    servingLabel: '1 tabak (150 g)',
    servingGrams: 150,
  },
  {
    id: 'usda-167535',
    name: 'Tortilla / lavaş',
    category: 'Tahıl ve ekmek',
    aliases: 'lavaş tortilla dürüm yufka',
    calories: 297,
    proteinG: 8,
    carbsG: 49.3,
    fatG: 7.6,
    servingLabel: '1 adet (49 g)',
    servingGrams: 49,
  },
  {
    id: 'usda-170438',
    name: 'Patates (haşlanmış)',
    category: 'Tahıl ve ekmek',
    aliases: 'patates haşlama potato',
    calories: 87,
    proteinG: 1.9,
    carbsG: 20.1,
    fatG: 0.1,
    servingLabel: '1 orta boy (150 g)',
    servingGrams: 150,
  },
  {
    id: 'usda-169264',
    name: 'Patates kızartması (fırında)',
    category: 'Tahıl ve ekmek',
    aliases: 'patates kızartması cips french fries',
    calories: 158,
    proteinG: 2.8,
    carbsG: 25.6,
    fatG: 5.5,
    servingLabel: '1 porsiyon (100 g)',
    servingGrams: 100,
  },
  {
    id: 'usda-168483',
    name: 'Tatlı patates (fırında)',
    category: 'Tahıl ve ekmek',
    aliases: 'tatlı patates sweet potato',
    calories: 90,
    proteinG: 2,
    carbsG: 20.7,
    fatG: 0.2,
    servingLabel: '1 orta boy (114 g)',
    servingGrams: 114,
  },
  {
    id: 'usda-169999',
    name: 'Mısır (haşlanmış)',
    category: 'Tahıl ve ekmek',
    aliases: 'mısır corn haşlanmış',
    calories: 96,
    proteinG: 3.4,
    carbsG: 21,
    fatG: 1.5,
    servingLabel: '1 su bardağı (164 g)',
    servingGrams: 164,
  },
  {
    id: 'usda-172421',
    name: 'Mercimek (pişmiş)',
    category: 'Baklagil',
    aliases: 'mercimek kırmızı yeşil lentil',
    calories: 116,
    proteinG: 9,
    carbsG: 20.1,
    fatG: 0.4,
    servingLabel: '1 kase (200 g)',
    servingGrams: 200,
  },
  {
    id: 'usda-173757',
    name: 'Nohut (pişmiş)',
    category: 'Baklagil',
    aliases: 'nohut chickpea garbanzo',
    calories: 164,
    proteinG: 8.9,
    carbsG: 27.4,
    fatG: 2.6,
    servingLabel: '1 su bardağı (164 g)',
    servingGrams: 164,
  },
  {
    id: 'usda-175203',
    name: 'Kuru fasulye (pişmiş)',
    category: 'Baklagil',
    aliases: 'kuru fasulye beyaz fasulye white beans',
    calories: 139,
    proteinG: 9.7,
    carbsG: 25.1,
    fatG: 0.4,
    servingLabel: '1 kase (179 g)',
    servingGrams: 179,
  },
  {
    id: 'usda-175194',
    name: 'Kırmızı fasulye (pişmiş)',
    category: 'Baklagil',
    aliases: 'kırmızı fasulye barbunya kidney beans',
    calories: 127,
    proteinG: 8.7,
    carbsG: 22.8,
    fatG: 0.5,
    servingLabel: '1 kase (177 g)',
    servingGrams: 177,
  },
  {
    id: 'usda-174289',
    name: 'Humus',
    category: 'Baklagil',
    aliases: 'humus hummus nohut ezmesi',
    calories: 237,
    proteinG: 7.8,
    carbsG: 15,
    fatG: 17.8,
    servingLabel: '2 yemek kaşığı (30 g)',
    servingGrams: 30,
  },
  {
    id: 'usda-170457',
    name: 'Domates',
    category: 'Sebze',
    aliases: 'domates tomato',
    calories: 18,
    proteinG: 0.9,
    carbsG: 3.9,
    fatG: 0.2,
    servingLabel: '1 orta boy (123 g)',
    servingGrams: 123,
  },
  {
    id: 'usda-168409',
    name: 'Salatalık',
    category: 'Sebze',
    aliases: 'salatalık hıyar cucumber',
    calories: 15,
    proteinG: 0.7,
    carbsG: 3.6,
    fatG: 0.1,
    servingLabel: '1 orta boy (200 g)',
    servingGrams: 200,
  },
  {
    id: 'usda-170427',
    name: 'Yeşil biber',
    category: 'Sebze',
    aliases: 'yeşil biber sivri biber dolmalık green pepper',
    calories: 20,
    proteinG: 0.9,
    carbsG: 4.6,
    fatG: 0.2,
    servingLabel: '1 orta boy (119 g)',
    servingGrams: 119,
  },
  {
    id: 'usda-170108',
    name: 'Kırmızı biber',
    category: 'Sebze',
    aliases: 'kırmızı biber kapya red pepper',
    calories: 26,
    proteinG: 1,
    carbsG: 6,
    fatG: 0.3,
    servingLabel: '1 orta boy (119 g)',
    servingGrams: 119,
  },
  {
    id: 'usda-169247',
    name: 'Marul',
    category: 'Sebze',
    aliases: 'marul yeşillik salata lettuce',
    calories: 17,
    proteinG: 1.2,
    carbsG: 3.3,
    fatG: 0.3,
    servingLabel: '1 kase (47 g)',
    servingGrams: 47,
  },
  {
    id: 'usda-168463',
    name: 'Ispanak (pişmiş)',
    category: 'Sebze',
    aliases: 'ıspanak spinach',
    calories: 23,
    proteinG: 3,
    carbsG: 3.8,
    fatG: 0.3,
    servingLabel: '1 kase (180 g)',
    servingGrams: 180,
  },
  {
    id: 'usda-169967',
    name: 'Brokoli (haşlanmış)',
    category: 'Sebze',
    aliases: 'brokoli broccoli',
    calories: 35,
    proteinG: 2.4,
    carbsG: 7.2,
    fatG: 0.4,
    servingLabel: '1 kase (156 g)',
    servingGrams: 156,
  },
  {
    id: 'usda-170393',
    name: 'Havuç (çiğ)',
    category: 'Sebze',
    aliases: 'havuç carrot',
    calories: 41,
    proteinG: 0.9,
    carbsG: 9.6,
    fatG: 0.2,
    servingLabel: '1 orta boy (61 g)',
    servingGrams: 61,
  },
  {
    id: 'usda-169291',
    name: 'Kabak (çiğ)',
    category: 'Sebze',
    aliases: 'kabak sakız kabağı zucchini',
    calories: 17,
    proteinG: 1.2,
    carbsG: 3.1,
    fatG: 0.3,
    servingLabel: '1 orta boy (196 g)',
    servingGrams: 196,
  },
  {
    id: 'usda-169229',
    name: 'Patlıcan (pişmiş)',
    category: 'Sebze',
    aliases: 'patlıcan eggplant',
    calories: 35,
    proteinG: 0.8,
    carbsG: 8.7,
    fatG: 0.2,
    servingLabel: '1 kase (99 g)',
    servingGrams: 99,
  },
  {
    id: 'usda-170397',
    name: 'Karnabahar (haşlanmış)',
    category: 'Sebze',
    aliases: 'karnabahar cauliflower',
    calories: 23,
    proteinG: 1.8,
    carbsG: 4.1,
    fatG: 0.5,
    servingLabel: '1 kase (124 g)',
    servingGrams: 124,
  },
  {
    id: 'usda-170000',
    name: 'Soğan',
    category: 'Sebze',
    aliases: 'soğan kuru soğan onion',
    calories: 40,
    proteinG: 1.1,
    carbsG: 9.3,
    fatG: 0.1,
    servingLabel: '1 orta boy (110 g)',
    servingGrams: 110,
  },
  {
    id: 'usda-169230',
    name: 'Sarımsak',
    category: 'Sebze',
    aliases: 'sarımsak garlic',
    calories: 149,
    proteinG: 6.4,
    carbsG: 33.1,
    fatG: 0.5,
    servingLabel: '1 diş (3 g)',
    servingGrams: 3,
  },
  {
    id: 'usda-169251',
    name: 'Mantar',
    category: 'Sebze',
    aliases: 'mantar kültür mantarı mushroom',
    calories: 22,
    proteinG: 3.1,
    carbsG: 3.3,
    fatG: 0.3,
    servingLabel: '1 su bardağı (70 g)',
    servingGrams: 70,
  },
  {
    id: 'usda-169141',
    name: 'Taze fasulye (haşlanmış)',
    category: 'Sebze',
    aliases: 'taze fasulye green beans',
    calories: 35,
    proteinG: 1.9,
    carbsG: 7.9,
    fatG: 0.3,
    servingLabel: '1 kase (125 g)',
    servingGrams: 125,
  },
  {
    id: 'usda-170420',
    name: 'Bezelye (haşlanmış)',
    category: 'Sebze',
    aliases: 'bezelye peas',
    calories: 84,
    proteinG: 5.4,
    carbsG: 15.6,
    fatG: 0.2,
    servingLabel: '1 kase (160 g)',
    servingGrams: 160,
  },
  {
    id: 'usda-169975',
    name: 'Lahana (çiğ)',
    category: 'Sebze',
    aliases: 'lahana beyaz lahana cabbage',
    calories: 25,
    proteinG: 1.3,
    carbsG: 5.8,
    fatG: 0.1,
    servingLabel: '1 su bardağı (70 g)',
    servingGrams: 70,
  },
  {
    id: 'usda-169146',
    name: 'Pancar (haşlanmış)',
    category: 'Sebze',
    aliases: 'pancar kırmızı pancar beet',
    calories: 44,
    proteinG: 1.7,
    carbsG: 10,
    fatG: 0.2,
    servingLabel: '1 su bardağı (170 g)',
    servingGrams: 170,
  },
  {
    id: 'usda-169094',
    name: 'Zeytin (siyah)',
    category: 'Sebze',
    aliases: 'zeytin siyah zeytin olive',
    calories: 116,
    proteinG: 0.8,
    carbsG: 6,
    fatG: 10.9,
    servingLabel: '5 adet (15 g)',
    servingGrams: 15,
  },
  {
    id: 'usda-171705',
    name: 'Avokado',
    category: 'Sebze',
    aliases: 'avokado avocado',
    calories: 160,
    proteinG: 2,
    carbsG: 8.5,
    fatG: 14.7,
    servingLabel: '1/2 adet (100 g)',
    servingGrams: 100,
  },
  {
    id: 'usda-171688',
    name: 'Elma',
    category: 'Meyve',
    aliases: 'elma apple',
    calories: 52,
    proteinG: 0.3,
    carbsG: 13.8,
    fatG: 0.2,
    servingLabel: '1 orta boy (182 g)',
    servingGrams: 182,
  },
  {
    id: 'usda-173944',
    name: 'Muz',
    category: 'Meyve',
    aliases: 'muz banana',
    calories: 89,
    proteinG: 1.1,
    carbsG: 22.8,
    fatG: 0.3,
    servingLabel: '1 orta boy (118 g)',
    servingGrams: 118,
  },
  {
    id: 'usda-169097',
    name: 'Portakal',
    category: 'Meyve',
    aliases: 'portakal orange',
    calories: 47,
    proteinG: 0.9,
    carbsG: 11.8,
    fatG: 0.1,
    servingLabel: '1 orta boy (131 g)',
    servingGrams: 131,
  },
  {
    id: 'usda-169105',
    name: 'Mandalina',
    category: 'Meyve',
    aliases: 'mandalina tangerine',
    calories: 53,
    proteinG: 0.8,
    carbsG: 13.3,
    fatG: 0.3,
    servingLabel: '1 orta boy (88 g)',
    servingGrams: 88,
  },
  {
    id: 'usda-174683',
    name: 'Üzüm',
    category: 'Meyve',
    aliases: 'üzüm grapes',
    calories: 69,
    proteinG: 0.7,
    carbsG: 18.1,
    fatG: 0.2,
    servingLabel: '1 avuç (92 g)',
    servingGrams: 92,
  },
  {
    id: 'usda-167762',
    name: 'Çilek',
    category: 'Meyve',
    aliases: 'çilek strawberry',
    calories: 32,
    proteinG: 0.7,
    carbsG: 7.7,
    fatG: 0.3,
    servingLabel: '1 kase (152 g)',
    servingGrams: 152,
  },
  {
    id: 'usda-167765',
    name: 'Karpuz',
    category: 'Meyve',
    aliases: 'karpuz watermelon',
    calories: 30,
    proteinG: 0.6,
    carbsG: 7.6,
    fatG: 0.2,
    servingLabel: '1 dilim (280 g)',
    servingGrams: 280,
  },
  {
    id: 'usda-169092',
    name: 'Kavun',
    category: 'Meyve',
    aliases: 'kavun melon cantaloupe',
    calories: 34,
    proteinG: 0.8,
    carbsG: 8.2,
    fatG: 0.2,
    servingLabel: '1 dilim (177 g)',
    servingGrams: 177,
  },
  {
    id: 'usda-169928',
    name: 'Şeftali',
    category: 'Meyve',
    aliases: 'şeftali peach',
    calories: 39,
    proteinG: 0.9,
    carbsG: 9.5,
    fatG: 0.3,
    servingLabel: '1 orta boy (150 g)',
    servingGrams: 150,
  },
  {
    id: 'usda-169118',
    name: 'Armut',
    category: 'Meyve',
    aliases: 'armut pear',
    calories: 57,
    proteinG: 0.4,
    carbsG: 15.2,
    fatG: 0.1,
    servingLabel: '1 orta boy (178 g)',
    servingGrams: 178,
  },
  {
    id: 'usda-171719',
    name: 'Kiraz',
    category: 'Meyve',
    aliases: 'kiraz cherry',
    calories: 63,
    proteinG: 1.1,
    carbsG: 16,
    fatG: 0.2,
    servingLabel: '1 avuç (138 g)',
    servingGrams: 138,
  },
  {
    id: 'usda-173954',
    name: 'Vişne',
    category: 'Meyve',
    aliases: 'vişne sour cherry',
    calories: 50,
    proteinG: 1,
    carbsG: 12.2,
    fatG: 0.3,
    servingLabel: '1 su bardağı (155 g)',
    servingGrams: 155,
  },
  {
    id: 'usda-171697',
    name: 'Kayısı (taze)',
    category: 'Meyve',
    aliases: 'kayısı apricot',
    calories: 48,
    proteinG: 1.4,
    carbsG: 11.1,
    fatG: 0.4,
    servingLabel: '1 adet (35 g)',
    servingGrams: 35,
  },
  {
    id: 'usda-173941',
    name: 'Kayısı kurusu',
    category: 'Meyve',
    aliases: 'kuru kayısı dried apricot',
    calories: 241,
    proteinG: 3.4,
    carbsG: 62.6,
    fatG: 0.5,
    servingLabel: '5 adet (35 g)',
    servingGrams: 35,
  },
  {
    id: 'usda-171726',
    name: 'Hurma',
    category: 'Meyve',
    aliases: 'hurma dates',
    calories: 282,
    proteinG: 2.5,
    carbsG: 75,
    fatG: 0.4,
    servingLabel: '3 adet (24 g)',
    servingGrams: 24,
  },
  {
    id: 'usda-174665',
    name: 'İncir (kuru)',
    category: 'Meyve',
    aliases: 'kuru incir fig dried',
    calories: 249,
    proteinG: 3.3,
    carbsG: 63.9,
    fatG: 0.9,
    servingLabel: '2 adet (19 g)',
    servingGrams: 19,
  },
  {
    id: 'usda-168165',
    name: 'Kuru üzüm',
    category: 'Meyve',
    aliases: 'kuru üzüm kuş üzümü raisin',
    calories: 299,
    proteinG: 3.3,
    carbsG: 79.3,
    fatG: 0.3,
    servingLabel: '1 avuç (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-169134',
    name: 'Nar',
    category: 'Meyve',
    aliases: 'nar pomegranate',
    calories: 83,
    proteinG: 1.7,
    carbsG: 18.7,
    fatG: 1.2,
    servingLabel: '1 adet (282 g)',
    servingGrams: 282,
  },
  {
    id: 'usda-168153',
    name: 'Kivi',
    category: 'Meyve',
    aliases: 'kivi kiwi',
    calories: 61,
    proteinG: 1.1,
    carbsG: 14.7,
    fatG: 0.5,
    servingLabel: '1 orta boy (76 g)',
    servingGrams: 76,
  },
  {
    id: 'usda-169124',
    name: 'Ananas',
    category: 'Meyve',
    aliases: 'ananas pineapple',
    calories: 50,
    proteinG: 0.5,
    carbsG: 13.1,
    fatG: 0.1,
    servingLabel: '1 dilim (84 g)',
    servingGrams: 84,
  },
  {
    id: 'usda-167746',
    name: 'Limon',
    category: 'Meyve',
    aliases: 'limon lemon',
    calories: 29,
    proteinG: 1.1,
    carbsG: 9.3,
    fatG: 0.3,
    servingLabel: '1 adet (58 g)',
    servingGrams: 58,
  },
  {
    id: 'usda-171711',
    name: 'Yaban mersini',
    category: 'Meyve',
    aliases: 'yaban mersini blueberry',
    calories: 57,
    proteinG: 0.7,
    carbsG: 14.5,
    fatG: 0.3,
    servingLabel: '1 kase (148 g)',
    servingGrams: 148,
  },
  {
    id: 'usda-169949',
    name: 'Erik',
    category: 'Meyve',
    aliases: 'erik plum',
    calories: 46,
    proteinG: 0.7,
    carbsG: 11.4,
    fatG: 0.3,
    servingLabel: '1 orta boy (66 g)',
    servingGrams: 66,
  },
  {
    id: 'usda-167755',
    name: 'Ahududu',
    category: 'Meyve',
    aliases: 'ahududu frambuaz raspberry',
    calories: 52,
    proteinG: 1.2,
    carbsG: 11.9,
    fatG: 0.7,
    servingLabel: '1 kase (123 g)',
    servingGrams: 123,
  },
  {
    id: 'usda-169910',
    name: 'Mango',
    category: 'Meyve',
    aliases: 'mango',
    calories: 60,
    proteinG: 0.8,
    carbsG: 15,
    fatG: 0.4,
    servingLabel: '1 adet (336 g)',
    servingGrams: 336,
  },
  {
    id: 'usda-170567',
    name: 'Badem',
    category: 'Kuruyemiş',
    aliases: 'badem almond',
    calories: 579,
    proteinG: 21.2,
    carbsG: 21.6,
    fatG: 49.9,
    servingLabel: '1 avuç (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-170187',
    name: 'Ceviz',
    category: 'Kuruyemiş',
    aliases: 'ceviz walnut',
    calories: 654,
    proteinG: 15.2,
    carbsG: 13.7,
    fatG: 65.2,
    servingLabel: '1 avuç (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-170581',
    name: 'Fındık',
    category: 'Kuruyemiş',
    aliases: 'fındık hazelnut',
    calories: 628,
    proteinG: 15,
    carbsG: 16.7,
    fatG: 60.8,
    servingLabel: '1 avuç (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-170184',
    name: 'Antep fıstığı',
    category: 'Kuruyemiş',
    aliases: 'antep fıstığı fıstık pistachio',
    calories: 560,
    proteinG: 20.2,
    carbsG: 27.2,
    fatG: 45.3,
    servingLabel: '1 avuç (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-170162',
    name: 'Kaju',
    category: 'Kuruyemiş',
    aliases: 'kaju cashew',
    calories: 553,
    proteinG: 18.2,
    carbsG: 30.2,
    fatG: 43.9,
    servingLabel: '1 avuç (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-174262',
    name: 'Yer fıstığı (kavrulmuş)',
    category: 'Kuruyemiş',
    aliases: 'yer fıstığı fıstık peanut',
    calories: 587,
    proteinG: 24.4,
    carbsG: 21.3,
    fatG: 49.7,
    servingLabel: '1 avuç (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-174266',
    name: 'Fıstık ezmesi',
    category: 'Kuruyemiş',
    aliases: 'fıstık ezmesi peanut butter',
    calories: 598,
    proteinG: 22.2,
    carbsG: 22.3,
    fatG: 51.4,
    servingLabel: '1 yemek kaşığı (16 g)',
    servingGrams: 16,
  },
  {
    id: 'usda-170562',
    name: 'Ayçekirdeği (çiğ)',
    category: 'Kuruyemiş',
    aliases: 'ayçekirdeği sunflower seeds çekirdek',
    calories: 584,
    proteinG: 20.8,
    carbsG: 20,
    fatG: 51.5,
    servingLabel: '1 avuç (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-170556',
    name: 'Kabak çekirdeği',
    category: 'Kuruyemiş',
    aliases: 'kabak çekirdeği pumpkin seeds',
    calories: 559,
    proteinG: 30.2,
    carbsG: 10.7,
    fatG: 49.1,
    servingLabel: '1 avuç (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-170554',
    name: 'Chia tohumu',
    category: 'Kuruyemiş',
    aliases: 'chia tohumu chia seeds',
    calories: 486,
    proteinG: 16.5,
    carbsG: 42.1,
    fatG: 30.7,
    servingLabel: '1 yemek kaşığı (12 g)',
    servingGrams: 12,
  },
  {
    id: 'usda-169414',
    name: 'Keten tohumu',
    category: 'Kuruyemiş',
    aliases: 'keten tohumu flaxseed',
    calories: 534,
    proteinG: 18.3,
    carbsG: 28.9,
    fatG: 42.2,
    servingLabel: '1 yemek kaşığı (10 g)',
    servingGrams: 10,
  },
  {
    id: 'usda-170150',
    name: 'Susam',
    category: 'Kuruyemiş',
    aliases: 'susam sesame',
    calories: 573,
    proteinG: 17.7,
    carbsG: 23.5,
    fatG: 49.7,
    servingLabel: '1 yemek kaşığı (9 g)',
    servingGrams: 9,
  },
  {
    id: 'usda-170189',
    name: 'Tahin',
    category: 'Kuruyemiş',
    aliases: 'tahin susam ezmesi tahini',
    calories: 595,
    proteinG: 17,
    carbsG: 21.2,
    fatG: 53.8,
    servingLabel: '1 yemek kaşığı (15 g)',
    servingGrams: 15,
  },
  {
    id: 'usda-171413',
    name: 'Zeytinyağı',
    category: 'Yağ ve sos',
    aliases: 'zeytinyağı olive oil',
    calories: 884,
    proteinG: 0,
    carbsG: 0,
    fatG: 100,
    servingLabel: '1 yemek kaşığı (14 g)',
    servingGrams: 14,
  },
  {
    id: 'usda-171017',
    name: 'Ayçiçek yağı',
    category: 'Yağ ve sos',
    aliases: 'ayçiçek yağı sıvı yağ sunflower oil',
    calories: 884,
    proteinG: 0,
    carbsG: 0,
    fatG: 100,
    servingLabel: '1 yemek kaşığı (14 g)',
    servingGrams: 14,
  },
  {
    id: 'usda-171009',
    name: 'Mayonez',
    category: 'Yağ ve sos',
    aliases: 'mayonez mayonnaise',
    calories: 680,
    proteinG: 1,
    carbsG: 0.6,
    fatG: 74.9,
    servingLabel: '1 yemek kaşığı (14 g)',
    servingGrams: 14,
  },
  {
    id: 'usda-168556',
    name: 'Ketçap',
    category: 'Yağ ve sos',
    aliases: 'ketçap ketchup',
    calories: 101,
    proteinG: 1,
    carbsG: 27.4,
    fatG: 0.1,
    servingLabel: '1 yemek kaşığı (17 g)',
    servingGrams: 17,
  },
  {
    id: 'usda-169640',
    name: 'Bal',
    category: 'Yağ ve sos',
    aliases: 'bal honey',
    calories: 304,
    proteinG: 0.3,
    carbsG: 82.4,
    fatG: 0,
    servingLabel: '1 yemek kaşığı (21 g)',
    servingGrams: 21,
  },
  {
    id: 'usda-169655',
    name: 'Toz şeker',
    category: 'Yağ ve sos',
    aliases: 'şeker toz şeker sugar',
    calories: 387,
    proteinG: 0,
    carbsG: 100,
    fatG: 0,
    servingLabel: '1 çay kaşığı (4 g)',
    servingGrams: 4,
  },
  {
    id: 'usda-169641',
    name: 'Reçel',
    category: 'Yağ ve sos',
    aliases: 'reçel jam marmelat',
    calories: 278,
    proteinG: 0.4,
    carbsG: 68.9,
    fatG: 0.1,
    servingLabel: '1 yemek kaşığı (20 g)',
    servingGrams: 20,
  },
  {
    id: 'usda-170273',
    name: 'Bitter çikolata (%70-85)',
    category: 'Tatlı ve atıştırmalık',
    aliases: 'bitter çikolata dark chocolate',
    calories: 598,
    proteinG: 7.8,
    carbsG: 45.9,
    fatG: 42.6,
    servingLabel: '3 kare (30 g)',
    servingGrams: 30,
  },
  {
    id: 'usda-167587',
    name: 'Sütlü çikolata',
    category: 'Tatlı ve atıştırmalık',
    aliases: 'sütlü çikolata milk chocolate',
    calories: 535,
    proteinG: 7.7,
    carbsG: 59.4,
    fatG: 29.7,
    servingLabel: '3 kare (30 g)',
    servingGrams: 30,
  },
  {
    id: 'usda-167575',
    name: 'Dondurma (vanilyalı)',
    category: 'Tatlı ve atıştırmalık',
    aliases: 'dondurma ice cream vanilya',
    calories: 207,
    proteinG: 3.5,
    carbsG: 23.6,
    fatG: 11,
    servingLabel: '1 top (66 g)',
    servingGrams: 66,
  },
  {
    id: 'usda-174950',
    name: 'Bisküvi (tereyağlı)',
    category: 'Tatlı ve atıştırmalık',
    aliases: 'bisküvi kurabiye cookie',
    calories: 467,
    proteinG: 6.1,
    carbsG: 68.9,
    fatG: 18.8,
    servingLabel: '3 adet (21 g)',
    servingGrams: 21,
  },
  {
    id: 'usda-169677',
    name: 'Patates cipsi',
    category: 'Tatlı ve atıştırmalık',
    aliases: 'cips patates cipsi chips',
    calories: 532,
    proteinG: 6.4,
    carbsG: 53.8,
    fatG: 34,
    servingLabel: '1 küçük paket (28 g)',
    servingGrams: 28,
  },
  {
    id: 'usda-167959',
    name: 'Patlamış mısır',
    category: 'Tatlı ve atıştırmalık',
    aliases: 'patlamış mısır popcorn',
    calories: 387,
    proteinG: 12.9,
    carbsG: 77.8,
    fatG: 4.5,
    servingLabel: '1 kase (8 g)',
    servingGrams: 8,
  },
  {
    id: 'usda-173227',
    name: 'Çay (şekersiz)',
    category: 'İçecek',
    aliases: 'çay siyah çay tea',
    calories: 1,
    proteinG: 0,
    carbsG: 0.3,
    fatG: 0,
    servingLabel: '1 bardak (100 g)',
    servingGrams: 100,
  },
  {
    id: 'usda-171890',
    name: 'Kahve (şekersiz)',
    category: 'İçecek',
    aliases: 'kahve filtre kahve coffee',
    calories: 1,
    proteinG: 0.1,
    carbsG: 0,
    fatG: 0,
    servingLabel: '1 fincan (237 g)',
    servingGrams: 237,
  },
  {
    id: 'usda-169098',
    name: 'Portakal suyu',
    category: 'İçecek',
    aliases: 'portakal suyu orange juice',
    calories: 45,
    proteinG: 0.7,
    carbsG: 10.4,
    fatG: 0.2,
    servingLabel: '1 su bardağı (248 g)',
    servingGrams: 248,
  },
  {
    id: 'usda-173933',
    name: 'Elma suyu',
    category: 'İçecek',
    aliases: 'elma suyu apple juice',
    calories: 46,
    proteinG: 0.1,
    carbsG: 11.3,
    fatG: 0.1,
    servingLabel: '1 su bardağı (248 g)',
    servingGrams: 248,
  },
  {
    id: 'usda-174852',
    name: 'Kola',
    category: 'İçecek',
    aliases: 'kola cola gazlı içecek',
    calories: 42,
    proteinG: 0,
    carbsG: 10.4,
    fatG: 0.3,
    servingLabel: '1 kutu (368 g)',
    servingGrams: 368,
  },
  {
    id: 'usda-168746',
    name: 'Bira',
    category: 'İçecek',
    aliases: 'bira beer',
    calories: 43,
    proteinG: 0.5,
    carbsG: 3.6,
    fatG: 0,
    servingLabel: '1 küçük şişe (356 g)',
    servingGrams: 356,
  },
  {
    id: 'usda-173190',
    name: 'Kırmızı şarap',
    category: 'İçecek',
    aliases: 'şarap kırmızı şarap wine',
    calories: 85,
    proteinG: 0.1,
    carbsG: 2.6,
    fatG: 0,
    servingLabel: '1 kadeh (147 g)',
    servingGrams: 147,
  },
];
